// dart format width=80
import 'dart:typed_data' as i2;
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class TSessions extends Table with TableInfo<TSessions, TSessionsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  TSessions(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> displayName = GeneratedColumn<String>(
    'display_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> startedAtUtc = GeneratedColumn<int>(
    'started_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> startedAtOffsetMinutes = GeneratedColumn<int>(
    'started_at_offset_minutes',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL CHECK (started_at_offset_minutes BETWEEN -720 AND 840)',
  );
  late final GeneratedColumn<int> stoppedAtUtc = GeneratedColumn<int>(
    'stopped_at_utc',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> stoppedAtOffsetMinutes = GeneratedColumn<int>(
    'stopped_at_offset_minutes',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> notes = GeneratedColumn<String>(
    'notes',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    displayName,
    status,
    startedAtUtc,
    startedAtOffsetMinutes,
    stoppedAtUtc,
    stoppedAtOffsetMinutes,
    notes,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 't_sessions';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  TSessionsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return TSessionsData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      displayName: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}display_name'],
      )!,
      status: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}status'],
      )!,
      startedAtUtc: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}started_at_utc'],
      )!,
      startedAtOffsetMinutes: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}started_at_offset_minutes'],
      )!,
      stoppedAtUtc: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}stopped_at_utc'],
      ),
      stoppedAtOffsetMinutes: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}stopped_at_offset_minutes'],
      ),
      notes: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}notes'],
      ),
    );
  }

  @override
  TSessions createAlias(String alias) {
    return TSessions(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class TSessionsData extends DataClass implements Insertable<TSessionsData> {
  final String id;
  final String displayName;
  final String status;
  final int startedAtUtc;
  final int startedAtOffsetMinutes;
  final int? stoppedAtUtc;
  final int? stoppedAtOffsetMinutes;
  final String? notes;
  const TSessionsData({
    required this.id,
    required this.displayName,
    required this.status,
    required this.startedAtUtc,
    required this.startedAtOffsetMinutes,
    this.stoppedAtUtc,
    this.stoppedAtOffsetMinutes,
    this.notes,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['display_name'] = Variable<String>(displayName);
    map['status'] = Variable<String>(status);
    map['started_at_utc'] = Variable<int>(startedAtUtc);
    map['started_at_offset_minutes'] = Variable<int>(startedAtOffsetMinutes);
    if (!nullToAbsent || stoppedAtUtc != null) {
      map['stopped_at_utc'] = Variable<int>(stoppedAtUtc);
    }
    if (!nullToAbsent || stoppedAtOffsetMinutes != null) {
      map['stopped_at_offset_minutes'] = Variable<int>(stoppedAtOffsetMinutes);
    }
    if (!nullToAbsent || notes != null) {
      map['notes'] = Variable<String>(notes);
    }
    return map;
  }

  TSessionsCompanion toCompanion(bool nullToAbsent) {
    return TSessionsCompanion(
      id: Value(id),
      displayName: Value(displayName),
      status: Value(status),
      startedAtUtc: Value(startedAtUtc),
      startedAtOffsetMinutes: Value(startedAtOffsetMinutes),
      stoppedAtUtc: stoppedAtUtc == null && nullToAbsent
          ? const Value.absent()
          : Value(stoppedAtUtc),
      stoppedAtOffsetMinutes: stoppedAtOffsetMinutes == null && nullToAbsent
          ? const Value.absent()
          : Value(stoppedAtOffsetMinutes),
      notes: notes == null && nullToAbsent
          ? const Value.absent()
          : Value(notes),
    );
  }

  factory TSessionsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return TSessionsData(
      id: serializer.fromJson<String>(json['id']),
      displayName: serializer.fromJson<String>(json['displayName']),
      status: serializer.fromJson<String>(json['status']),
      startedAtUtc: serializer.fromJson<int>(json['startedAtUtc']),
      startedAtOffsetMinutes: serializer.fromJson<int>(
        json['startedAtOffsetMinutes'],
      ),
      stoppedAtUtc: serializer.fromJson<int?>(json['stoppedAtUtc']),
      stoppedAtOffsetMinutes: serializer.fromJson<int?>(
        json['stoppedAtOffsetMinutes'],
      ),
      notes: serializer.fromJson<String?>(json['notes']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'displayName': serializer.toJson<String>(displayName),
      'status': serializer.toJson<String>(status),
      'startedAtUtc': serializer.toJson<int>(startedAtUtc),
      'startedAtOffsetMinutes': serializer.toJson<int>(startedAtOffsetMinutes),
      'stoppedAtUtc': serializer.toJson<int?>(stoppedAtUtc),
      'stoppedAtOffsetMinutes': serializer.toJson<int?>(stoppedAtOffsetMinutes),
      'notes': serializer.toJson<String?>(notes),
    };
  }

  TSessionsData copyWith({
    String? id,
    String? displayName,
    String? status,
    int? startedAtUtc,
    int? startedAtOffsetMinutes,
    Value<int?> stoppedAtUtc = const Value.absent(),
    Value<int?> stoppedAtOffsetMinutes = const Value.absent(),
    Value<String?> notes = const Value.absent(),
  }) => TSessionsData(
    id: id ?? this.id,
    displayName: displayName ?? this.displayName,
    status: status ?? this.status,
    startedAtUtc: startedAtUtc ?? this.startedAtUtc,
    startedAtOffsetMinutes:
        startedAtOffsetMinutes ?? this.startedAtOffsetMinutes,
    stoppedAtUtc: stoppedAtUtc.present ? stoppedAtUtc.value : this.stoppedAtUtc,
    stoppedAtOffsetMinutes: stoppedAtOffsetMinutes.present
        ? stoppedAtOffsetMinutes.value
        : this.stoppedAtOffsetMinutes,
    notes: notes.present ? notes.value : this.notes,
  );
  TSessionsData copyWithCompanion(TSessionsCompanion data) {
    return TSessionsData(
      id: data.id.present ? data.id.value : this.id,
      displayName: data.displayName.present
          ? data.displayName.value
          : this.displayName,
      status: data.status.present ? data.status.value : this.status,
      startedAtUtc: data.startedAtUtc.present
          ? data.startedAtUtc.value
          : this.startedAtUtc,
      startedAtOffsetMinutes: data.startedAtOffsetMinutes.present
          ? data.startedAtOffsetMinutes.value
          : this.startedAtOffsetMinutes,
      stoppedAtUtc: data.stoppedAtUtc.present
          ? data.stoppedAtUtc.value
          : this.stoppedAtUtc,
      stoppedAtOffsetMinutes: data.stoppedAtOffsetMinutes.present
          ? data.stoppedAtOffsetMinutes.value
          : this.stoppedAtOffsetMinutes,
      notes: data.notes.present ? data.notes.value : this.notes,
    );
  }

  @override
  String toString() {
    return (StringBuffer('TSessionsData(')
          ..write('id: $id, ')
          ..write('displayName: $displayName, ')
          ..write('status: $status, ')
          ..write('startedAtUtc: $startedAtUtc, ')
          ..write('startedAtOffsetMinutes: $startedAtOffsetMinutes, ')
          ..write('stoppedAtUtc: $stoppedAtUtc, ')
          ..write('stoppedAtOffsetMinutes: $stoppedAtOffsetMinutes, ')
          ..write('notes: $notes')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    displayName,
    status,
    startedAtUtc,
    startedAtOffsetMinutes,
    stoppedAtUtc,
    stoppedAtOffsetMinutes,
    notes,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is TSessionsData &&
          other.id == this.id &&
          other.displayName == this.displayName &&
          other.status == this.status &&
          other.startedAtUtc == this.startedAtUtc &&
          other.startedAtOffsetMinutes == this.startedAtOffsetMinutes &&
          other.stoppedAtUtc == this.stoppedAtUtc &&
          other.stoppedAtOffsetMinutes == this.stoppedAtOffsetMinutes &&
          other.notes == this.notes);
}

class TSessionsCompanion extends UpdateCompanion<TSessionsData> {
  final Value<String> id;
  final Value<String> displayName;
  final Value<String> status;
  final Value<int> startedAtUtc;
  final Value<int> startedAtOffsetMinutes;
  final Value<int?> stoppedAtUtc;
  final Value<int?> stoppedAtOffsetMinutes;
  final Value<String?> notes;
  final Value<int> rowid;
  const TSessionsCompanion({
    this.id = const Value.absent(),
    this.displayName = const Value.absent(),
    this.status = const Value.absent(),
    this.startedAtUtc = const Value.absent(),
    this.startedAtOffsetMinutes = const Value.absent(),
    this.stoppedAtUtc = const Value.absent(),
    this.stoppedAtOffsetMinutes = const Value.absent(),
    this.notes = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  TSessionsCompanion.insert({
    required String id,
    required String displayName,
    required String status,
    required int startedAtUtc,
    required int startedAtOffsetMinutes,
    this.stoppedAtUtc = const Value.absent(),
    this.stoppedAtOffsetMinutes = const Value.absent(),
    this.notes = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       displayName = Value(displayName),
       status = Value(status),
       startedAtUtc = Value(startedAtUtc),
       startedAtOffsetMinutes = Value(startedAtOffsetMinutes);
  static Insertable<TSessionsData> custom({
    Expression<String>? id,
    Expression<String>? displayName,
    Expression<String>? status,
    Expression<int>? startedAtUtc,
    Expression<int>? startedAtOffsetMinutes,
    Expression<int>? stoppedAtUtc,
    Expression<int>? stoppedAtOffsetMinutes,
    Expression<String>? notes,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (displayName != null) 'display_name': displayName,
      if (status != null) 'status': status,
      if (startedAtUtc != null) 'started_at_utc': startedAtUtc,
      if (startedAtOffsetMinutes != null)
        'started_at_offset_minutes': startedAtOffsetMinutes,
      if (stoppedAtUtc != null) 'stopped_at_utc': stoppedAtUtc,
      if (stoppedAtOffsetMinutes != null)
        'stopped_at_offset_minutes': stoppedAtOffsetMinutes,
      if (notes != null) 'notes': notes,
      if (rowid != null) 'rowid': rowid,
    });
  }

  TSessionsCompanion copyWith({
    Value<String>? id,
    Value<String>? displayName,
    Value<String>? status,
    Value<int>? startedAtUtc,
    Value<int>? startedAtOffsetMinutes,
    Value<int?>? stoppedAtUtc,
    Value<int?>? stoppedAtOffsetMinutes,
    Value<String?>? notes,
    Value<int>? rowid,
  }) {
    return TSessionsCompanion(
      id: id ?? this.id,
      displayName: displayName ?? this.displayName,
      status: status ?? this.status,
      startedAtUtc: startedAtUtc ?? this.startedAtUtc,
      startedAtOffsetMinutes:
          startedAtOffsetMinutes ?? this.startedAtOffsetMinutes,
      stoppedAtUtc: stoppedAtUtc ?? this.stoppedAtUtc,
      stoppedAtOffsetMinutes:
          stoppedAtOffsetMinutes ?? this.stoppedAtOffsetMinutes,
      notes: notes ?? this.notes,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (displayName.present) {
      map['display_name'] = Variable<String>(displayName.value);
    }
    if (status.present) {
      map['status'] = Variable<String>(status.value);
    }
    if (startedAtUtc.present) {
      map['started_at_utc'] = Variable<int>(startedAtUtc.value);
    }
    if (startedAtOffsetMinutes.present) {
      map['started_at_offset_minutes'] = Variable<int>(
        startedAtOffsetMinutes.value,
      );
    }
    if (stoppedAtUtc.present) {
      map['stopped_at_utc'] = Variable<int>(stoppedAtUtc.value);
    }
    if (stoppedAtOffsetMinutes.present) {
      map['stopped_at_offset_minutes'] = Variable<int>(
        stoppedAtOffsetMinutes.value,
      );
    }
    if (notes.present) {
      map['notes'] = Variable<String>(notes.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('TSessionsCompanion(')
          ..write('id: $id, ')
          ..write('displayName: $displayName, ')
          ..write('status: $status, ')
          ..write('startedAtUtc: $startedAtUtc, ')
          ..write('startedAtOffsetMinutes: $startedAtOffsetMinutes, ')
          ..write('stoppedAtUtc: $stoppedAtUtc, ')
          ..write('stoppedAtOffsetMinutes: $stoppedAtOffsetMinutes, ')
          ..write('notes: $notes, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class TMarkerCategories extends Table
    with TableInfo<TMarkerCategories, TMarkerCategoriesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  TMarkerCategories(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> displayName = GeneratedColumn<String>(
    'display_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> iconName = GeneratedColumn<String>(
    'icon_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> createdAtUtc = GeneratedColumn<int>(
    'created_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> createdAtOffsetMinutes = GeneratedColumn<int>(
    'created_at_offset_minutes',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    displayName,
    iconName,
    createdAtUtc,
    createdAtOffsetMinutes,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 't_marker_categories';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  TMarkerCategoriesData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return TMarkerCategoriesData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      displayName: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}display_name'],
      )!,
      iconName: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}icon_name'],
      )!,
      createdAtUtc: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at_utc'],
      )!,
      createdAtOffsetMinutes: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at_offset_minutes'],
      )!,
    );
  }

  @override
  TMarkerCategories createAlias(String alias) {
    return TMarkerCategories(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class TMarkerCategoriesData extends DataClass
    implements Insertable<TMarkerCategoriesData> {
  final String id;
  final String displayName;
  final String iconName;
  final int createdAtUtc;
  final int createdAtOffsetMinutes;
  const TMarkerCategoriesData({
    required this.id,
    required this.displayName,
    required this.iconName,
    required this.createdAtUtc,
    required this.createdAtOffsetMinutes,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['display_name'] = Variable<String>(displayName);
    map['icon_name'] = Variable<String>(iconName);
    map['created_at_utc'] = Variable<int>(createdAtUtc);
    map['created_at_offset_minutes'] = Variable<int>(createdAtOffsetMinutes);
    return map;
  }

  TMarkerCategoriesCompanion toCompanion(bool nullToAbsent) {
    return TMarkerCategoriesCompanion(
      id: Value(id),
      displayName: Value(displayName),
      iconName: Value(iconName),
      createdAtUtc: Value(createdAtUtc),
      createdAtOffsetMinutes: Value(createdAtOffsetMinutes),
    );
  }

  factory TMarkerCategoriesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return TMarkerCategoriesData(
      id: serializer.fromJson<String>(json['id']),
      displayName: serializer.fromJson<String>(json['displayName']),
      iconName: serializer.fromJson<String>(json['iconName']),
      createdAtUtc: serializer.fromJson<int>(json['createdAtUtc']),
      createdAtOffsetMinutes: serializer.fromJson<int>(
        json['createdAtOffsetMinutes'],
      ),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'displayName': serializer.toJson<String>(displayName),
      'iconName': serializer.toJson<String>(iconName),
      'createdAtUtc': serializer.toJson<int>(createdAtUtc),
      'createdAtOffsetMinutes': serializer.toJson<int>(createdAtOffsetMinutes),
    };
  }

  TMarkerCategoriesData copyWith({
    String? id,
    String? displayName,
    String? iconName,
    int? createdAtUtc,
    int? createdAtOffsetMinutes,
  }) => TMarkerCategoriesData(
    id: id ?? this.id,
    displayName: displayName ?? this.displayName,
    iconName: iconName ?? this.iconName,
    createdAtUtc: createdAtUtc ?? this.createdAtUtc,
    createdAtOffsetMinutes:
        createdAtOffsetMinutes ?? this.createdAtOffsetMinutes,
  );
  TMarkerCategoriesData copyWithCompanion(TMarkerCategoriesCompanion data) {
    return TMarkerCategoriesData(
      id: data.id.present ? data.id.value : this.id,
      displayName: data.displayName.present
          ? data.displayName.value
          : this.displayName,
      iconName: data.iconName.present ? data.iconName.value : this.iconName,
      createdAtUtc: data.createdAtUtc.present
          ? data.createdAtUtc.value
          : this.createdAtUtc,
      createdAtOffsetMinutes: data.createdAtOffsetMinutes.present
          ? data.createdAtOffsetMinutes.value
          : this.createdAtOffsetMinutes,
    );
  }

  @override
  String toString() {
    return (StringBuffer('TMarkerCategoriesData(')
          ..write('id: $id, ')
          ..write('displayName: $displayName, ')
          ..write('iconName: $iconName, ')
          ..write('createdAtUtc: $createdAtUtc, ')
          ..write('createdAtOffsetMinutes: $createdAtOffsetMinutes')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    displayName,
    iconName,
    createdAtUtc,
    createdAtOffsetMinutes,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is TMarkerCategoriesData &&
          other.id == this.id &&
          other.displayName == this.displayName &&
          other.iconName == this.iconName &&
          other.createdAtUtc == this.createdAtUtc &&
          other.createdAtOffsetMinutes == this.createdAtOffsetMinutes);
}

class TMarkerCategoriesCompanion
    extends UpdateCompanion<TMarkerCategoriesData> {
  final Value<String> id;
  final Value<String> displayName;
  final Value<String> iconName;
  final Value<int> createdAtUtc;
  final Value<int> createdAtOffsetMinutes;
  final Value<int> rowid;
  const TMarkerCategoriesCompanion({
    this.id = const Value.absent(),
    this.displayName = const Value.absent(),
    this.iconName = const Value.absent(),
    this.createdAtUtc = const Value.absent(),
    this.createdAtOffsetMinutes = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  TMarkerCategoriesCompanion.insert({
    required String id,
    required String displayName,
    required String iconName,
    required int createdAtUtc,
    required int createdAtOffsetMinutes,
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       displayName = Value(displayName),
       iconName = Value(iconName),
       createdAtUtc = Value(createdAtUtc),
       createdAtOffsetMinutes = Value(createdAtOffsetMinutes);
  static Insertable<TMarkerCategoriesData> custom({
    Expression<String>? id,
    Expression<String>? displayName,
    Expression<String>? iconName,
    Expression<int>? createdAtUtc,
    Expression<int>? createdAtOffsetMinutes,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (displayName != null) 'display_name': displayName,
      if (iconName != null) 'icon_name': iconName,
      if (createdAtUtc != null) 'created_at_utc': createdAtUtc,
      if (createdAtOffsetMinutes != null)
        'created_at_offset_minutes': createdAtOffsetMinutes,
      if (rowid != null) 'rowid': rowid,
    });
  }

  TMarkerCategoriesCompanion copyWith({
    Value<String>? id,
    Value<String>? displayName,
    Value<String>? iconName,
    Value<int>? createdAtUtc,
    Value<int>? createdAtOffsetMinutes,
    Value<int>? rowid,
  }) {
    return TMarkerCategoriesCompanion(
      id: id ?? this.id,
      displayName: displayName ?? this.displayName,
      iconName: iconName ?? this.iconName,
      createdAtUtc: createdAtUtc ?? this.createdAtUtc,
      createdAtOffsetMinutes:
          createdAtOffsetMinutes ?? this.createdAtOffsetMinutes,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (displayName.present) {
      map['display_name'] = Variable<String>(displayName.value);
    }
    if (iconName.present) {
      map['icon_name'] = Variable<String>(iconName.value);
    }
    if (createdAtUtc.present) {
      map['created_at_utc'] = Variable<int>(createdAtUtc.value);
    }
    if (createdAtOffsetMinutes.present) {
      map['created_at_offset_minutes'] = Variable<int>(
        createdAtOffsetMinutes.value,
      );
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('TMarkerCategoriesCompanion(')
          ..write('id: $id, ')
          ..write('displayName: $displayName, ')
          ..write('iconName: $iconName, ')
          ..write('createdAtUtc: $createdAtUtc, ')
          ..write('createdAtOffsetMinutes: $createdAtOffsetMinutes, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class TMarkers extends Table with TableInfo<TMarkers, TMarkersData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  TMarkers(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> sessionId = GeneratedColumn<String>(
    'session_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES t_sessions(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<String> categoryId = GeneratedColumn<String>(
    'category_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES t_marker_categories(id)',
  );
  late final GeneratedColumn<double> lat = GeneratedColumn<double>(
    'lat',
    aliasedName,
    false,
    type: DriftSqlType.double,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<double> lon = GeneratedColumn<double>(
    'lon',
    aliasedName,
    false,
    type: DriftSqlType.double,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> title = GeneratedColumn<String>(
    'title',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> notes = GeneratedColumn<String>(
    'notes',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> createdAtUtc = GeneratedColumn<int>(
    'created_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> createdAtOffsetMinutes = GeneratedColumn<int>(
    'created_at_offset_minutes',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    sessionId,
    categoryId,
    lat,
    lon,
    title,
    notes,
    createdAtUtc,
    createdAtOffsetMinutes,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 't_markers';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  TMarkersData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return TMarkersData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      sessionId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}session_id'],
      )!,
      categoryId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}category_id'],
      )!,
      lat: attachedDatabase.typeMapping.read(
        DriftSqlType.double,
        data['${effectivePrefix}lat'],
      )!,
      lon: attachedDatabase.typeMapping.read(
        DriftSqlType.double,
        data['${effectivePrefix}lon'],
      )!,
      title: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}title'],
      )!,
      notes: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}notes'],
      ),
      createdAtUtc: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at_utc'],
      )!,
      createdAtOffsetMinutes: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at_offset_minutes'],
      )!,
    );
  }

  @override
  TMarkers createAlias(String alias) {
    return TMarkers(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class TMarkersData extends DataClass implements Insertable<TMarkersData> {
  final String id;
  final String sessionId;
  final String categoryId;
  final double lat;
  final double lon;
  final String title;
  final String? notes;
  final int createdAtUtc;
  final int createdAtOffsetMinutes;
  const TMarkersData({
    required this.id,
    required this.sessionId,
    required this.categoryId,
    required this.lat,
    required this.lon,
    required this.title,
    this.notes,
    required this.createdAtUtc,
    required this.createdAtOffsetMinutes,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['session_id'] = Variable<String>(sessionId);
    map['category_id'] = Variable<String>(categoryId);
    map['lat'] = Variable<double>(lat);
    map['lon'] = Variable<double>(lon);
    map['title'] = Variable<String>(title);
    if (!nullToAbsent || notes != null) {
      map['notes'] = Variable<String>(notes);
    }
    map['created_at_utc'] = Variable<int>(createdAtUtc);
    map['created_at_offset_minutes'] = Variable<int>(createdAtOffsetMinutes);
    return map;
  }

  TMarkersCompanion toCompanion(bool nullToAbsent) {
    return TMarkersCompanion(
      id: Value(id),
      sessionId: Value(sessionId),
      categoryId: Value(categoryId),
      lat: Value(lat),
      lon: Value(lon),
      title: Value(title),
      notes: notes == null && nullToAbsent
          ? const Value.absent()
          : Value(notes),
      createdAtUtc: Value(createdAtUtc),
      createdAtOffsetMinutes: Value(createdAtOffsetMinutes),
    );
  }

  factory TMarkersData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return TMarkersData(
      id: serializer.fromJson<String>(json['id']),
      sessionId: serializer.fromJson<String>(json['sessionId']),
      categoryId: serializer.fromJson<String>(json['categoryId']),
      lat: serializer.fromJson<double>(json['lat']),
      lon: serializer.fromJson<double>(json['lon']),
      title: serializer.fromJson<String>(json['title']),
      notes: serializer.fromJson<String?>(json['notes']),
      createdAtUtc: serializer.fromJson<int>(json['createdAtUtc']),
      createdAtOffsetMinutes: serializer.fromJson<int>(
        json['createdAtOffsetMinutes'],
      ),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'sessionId': serializer.toJson<String>(sessionId),
      'categoryId': serializer.toJson<String>(categoryId),
      'lat': serializer.toJson<double>(lat),
      'lon': serializer.toJson<double>(lon),
      'title': serializer.toJson<String>(title),
      'notes': serializer.toJson<String?>(notes),
      'createdAtUtc': serializer.toJson<int>(createdAtUtc),
      'createdAtOffsetMinutes': serializer.toJson<int>(createdAtOffsetMinutes),
    };
  }

  TMarkersData copyWith({
    String? id,
    String? sessionId,
    String? categoryId,
    double? lat,
    double? lon,
    String? title,
    Value<String?> notes = const Value.absent(),
    int? createdAtUtc,
    int? createdAtOffsetMinutes,
  }) => TMarkersData(
    id: id ?? this.id,
    sessionId: sessionId ?? this.sessionId,
    categoryId: categoryId ?? this.categoryId,
    lat: lat ?? this.lat,
    lon: lon ?? this.lon,
    title: title ?? this.title,
    notes: notes.present ? notes.value : this.notes,
    createdAtUtc: createdAtUtc ?? this.createdAtUtc,
    createdAtOffsetMinutes:
        createdAtOffsetMinutes ?? this.createdAtOffsetMinutes,
  );
  TMarkersData copyWithCompanion(TMarkersCompanion data) {
    return TMarkersData(
      id: data.id.present ? data.id.value : this.id,
      sessionId: data.sessionId.present ? data.sessionId.value : this.sessionId,
      categoryId: data.categoryId.present
          ? data.categoryId.value
          : this.categoryId,
      lat: data.lat.present ? data.lat.value : this.lat,
      lon: data.lon.present ? data.lon.value : this.lon,
      title: data.title.present ? data.title.value : this.title,
      notes: data.notes.present ? data.notes.value : this.notes,
      createdAtUtc: data.createdAtUtc.present
          ? data.createdAtUtc.value
          : this.createdAtUtc,
      createdAtOffsetMinutes: data.createdAtOffsetMinutes.present
          ? data.createdAtOffsetMinutes.value
          : this.createdAtOffsetMinutes,
    );
  }

  @override
  String toString() {
    return (StringBuffer('TMarkersData(')
          ..write('id: $id, ')
          ..write('sessionId: $sessionId, ')
          ..write('categoryId: $categoryId, ')
          ..write('lat: $lat, ')
          ..write('lon: $lon, ')
          ..write('title: $title, ')
          ..write('notes: $notes, ')
          ..write('createdAtUtc: $createdAtUtc, ')
          ..write('createdAtOffsetMinutes: $createdAtOffsetMinutes')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    sessionId,
    categoryId,
    lat,
    lon,
    title,
    notes,
    createdAtUtc,
    createdAtOffsetMinutes,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is TMarkersData &&
          other.id == this.id &&
          other.sessionId == this.sessionId &&
          other.categoryId == this.categoryId &&
          other.lat == this.lat &&
          other.lon == this.lon &&
          other.title == this.title &&
          other.notes == this.notes &&
          other.createdAtUtc == this.createdAtUtc &&
          other.createdAtOffsetMinutes == this.createdAtOffsetMinutes);
}

class TMarkersCompanion extends UpdateCompanion<TMarkersData> {
  final Value<String> id;
  final Value<String> sessionId;
  final Value<String> categoryId;
  final Value<double> lat;
  final Value<double> lon;
  final Value<String> title;
  final Value<String?> notes;
  final Value<int> createdAtUtc;
  final Value<int> createdAtOffsetMinutes;
  final Value<int> rowid;
  const TMarkersCompanion({
    this.id = const Value.absent(),
    this.sessionId = const Value.absent(),
    this.categoryId = const Value.absent(),
    this.lat = const Value.absent(),
    this.lon = const Value.absent(),
    this.title = const Value.absent(),
    this.notes = const Value.absent(),
    this.createdAtUtc = const Value.absent(),
    this.createdAtOffsetMinutes = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  TMarkersCompanion.insert({
    required String id,
    required String sessionId,
    required String categoryId,
    required double lat,
    required double lon,
    required String title,
    this.notes = const Value.absent(),
    required int createdAtUtc,
    required int createdAtOffsetMinutes,
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       sessionId = Value(sessionId),
       categoryId = Value(categoryId),
       lat = Value(lat),
       lon = Value(lon),
       title = Value(title),
       createdAtUtc = Value(createdAtUtc),
       createdAtOffsetMinutes = Value(createdAtOffsetMinutes);
  static Insertable<TMarkersData> custom({
    Expression<String>? id,
    Expression<String>? sessionId,
    Expression<String>? categoryId,
    Expression<double>? lat,
    Expression<double>? lon,
    Expression<String>? title,
    Expression<String>? notes,
    Expression<int>? createdAtUtc,
    Expression<int>? createdAtOffsetMinutes,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (sessionId != null) 'session_id': sessionId,
      if (categoryId != null) 'category_id': categoryId,
      if (lat != null) 'lat': lat,
      if (lon != null) 'lon': lon,
      if (title != null) 'title': title,
      if (notes != null) 'notes': notes,
      if (createdAtUtc != null) 'created_at_utc': createdAtUtc,
      if (createdAtOffsetMinutes != null)
        'created_at_offset_minutes': createdAtOffsetMinutes,
      if (rowid != null) 'rowid': rowid,
    });
  }

  TMarkersCompanion copyWith({
    Value<String>? id,
    Value<String>? sessionId,
    Value<String>? categoryId,
    Value<double>? lat,
    Value<double>? lon,
    Value<String>? title,
    Value<String?>? notes,
    Value<int>? createdAtUtc,
    Value<int>? createdAtOffsetMinutes,
    Value<int>? rowid,
  }) {
    return TMarkersCompanion(
      id: id ?? this.id,
      sessionId: sessionId ?? this.sessionId,
      categoryId: categoryId ?? this.categoryId,
      lat: lat ?? this.lat,
      lon: lon ?? this.lon,
      title: title ?? this.title,
      notes: notes ?? this.notes,
      createdAtUtc: createdAtUtc ?? this.createdAtUtc,
      createdAtOffsetMinutes:
          createdAtOffsetMinutes ?? this.createdAtOffsetMinutes,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (sessionId.present) {
      map['session_id'] = Variable<String>(sessionId.value);
    }
    if (categoryId.present) {
      map['category_id'] = Variable<String>(categoryId.value);
    }
    if (lat.present) {
      map['lat'] = Variable<double>(lat.value);
    }
    if (lon.present) {
      map['lon'] = Variable<double>(lon.value);
    }
    if (title.present) {
      map['title'] = Variable<String>(title.value);
    }
    if (notes.present) {
      map['notes'] = Variable<String>(notes.value);
    }
    if (createdAtUtc.present) {
      map['created_at_utc'] = Variable<int>(createdAtUtc.value);
    }
    if (createdAtOffsetMinutes.present) {
      map['created_at_offset_minutes'] = Variable<int>(
        createdAtOffsetMinutes.value,
      );
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('TMarkersCompanion(')
          ..write('id: $id, ')
          ..write('sessionId: $sessionId, ')
          ..write('categoryId: $categoryId, ')
          ..write('lat: $lat, ')
          ..write('lon: $lon, ')
          ..write('title: $title, ')
          ..write('notes: $notes, ')
          ..write('createdAtUtc: $createdAtUtc, ')
          ..write('createdAtOffsetMinutes: $createdAtOffsetMinutes, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class TRevealedTiles extends Table
    with TableInfo<TRevealedTiles, TRevealedTilesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  TRevealedTiles(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> sessionId = GeneratedColumn<String>(
    'session_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES t_sessions(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<int> parentX = GeneratedColumn<int>(
    'parent_x',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> parentY = GeneratedColumn<int>(
    'parent_y',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> parentZoom = GeneratedColumn<int>(
    'parent_zoom',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 14',
    defaultValue: const CustomExpression('14'),
  );
  late final GeneratedColumn<i2.Uint8List> bitmap =
      GeneratedColumn<i2.Uint8List>(
        'bitmap',
        aliasedName,
        false,
        type: DriftSqlType.blob,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<int> setBitCount = GeneratedColumn<int>(
    'set_bit_count',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> updatedAtUtc = GeneratedColumn<int>(
    'updated_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    sessionId,
    parentX,
    parentY,
    parentZoom,
    bitmap,
    setBitCount,
    updatedAtUtc,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 't_revealed_tiles';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {sessionId, parentX, parentY, parentZoom},
  ];
  @override
  TRevealedTilesData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return TRevealedTilesData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      sessionId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}session_id'],
      )!,
      parentX: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}parent_x'],
      )!,
      parentY: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}parent_y'],
      )!,
      parentZoom: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}parent_zoom'],
      )!,
      bitmap: attachedDatabase.typeMapping.read(
        DriftSqlType.blob,
        data['${effectivePrefix}bitmap'],
      )!,
      setBitCount: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}set_bit_count'],
      )!,
      updatedAtUtc: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}updated_at_utc'],
      )!,
    );
  }

  @override
  TRevealedTiles createAlias(String alias) {
    return TRevealedTiles(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(id)',
    'UNIQUE(session_id, parent_x, parent_y, parent_zoom)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class TRevealedTilesData extends DataClass
    implements Insertable<TRevealedTilesData> {
  final String id;
  final String sessionId;
  final int parentX;
  final int parentY;
  final int parentZoom;
  final i2.Uint8List bitmap;
  final int setBitCount;
  final int updatedAtUtc;
  const TRevealedTilesData({
    required this.id,
    required this.sessionId,
    required this.parentX,
    required this.parentY,
    required this.parentZoom,
    required this.bitmap,
    required this.setBitCount,
    required this.updatedAtUtc,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['session_id'] = Variable<String>(sessionId);
    map['parent_x'] = Variable<int>(parentX);
    map['parent_y'] = Variable<int>(parentY);
    map['parent_zoom'] = Variable<int>(parentZoom);
    map['bitmap'] = Variable<i2.Uint8List>(bitmap);
    map['set_bit_count'] = Variable<int>(setBitCount);
    map['updated_at_utc'] = Variable<int>(updatedAtUtc);
    return map;
  }

  TRevealedTilesCompanion toCompanion(bool nullToAbsent) {
    return TRevealedTilesCompanion(
      id: Value(id),
      sessionId: Value(sessionId),
      parentX: Value(parentX),
      parentY: Value(parentY),
      parentZoom: Value(parentZoom),
      bitmap: Value(bitmap),
      setBitCount: Value(setBitCount),
      updatedAtUtc: Value(updatedAtUtc),
    );
  }

  factory TRevealedTilesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return TRevealedTilesData(
      id: serializer.fromJson<String>(json['id']),
      sessionId: serializer.fromJson<String>(json['sessionId']),
      parentX: serializer.fromJson<int>(json['parentX']),
      parentY: serializer.fromJson<int>(json['parentY']),
      parentZoom: serializer.fromJson<int>(json['parentZoom']),
      bitmap: serializer.fromJson<i2.Uint8List>(json['bitmap']),
      setBitCount: serializer.fromJson<int>(json['setBitCount']),
      updatedAtUtc: serializer.fromJson<int>(json['updatedAtUtc']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'sessionId': serializer.toJson<String>(sessionId),
      'parentX': serializer.toJson<int>(parentX),
      'parentY': serializer.toJson<int>(parentY),
      'parentZoom': serializer.toJson<int>(parentZoom),
      'bitmap': serializer.toJson<i2.Uint8List>(bitmap),
      'setBitCount': serializer.toJson<int>(setBitCount),
      'updatedAtUtc': serializer.toJson<int>(updatedAtUtc),
    };
  }

  TRevealedTilesData copyWith({
    String? id,
    String? sessionId,
    int? parentX,
    int? parentY,
    int? parentZoom,
    i2.Uint8List? bitmap,
    int? setBitCount,
    int? updatedAtUtc,
  }) => TRevealedTilesData(
    id: id ?? this.id,
    sessionId: sessionId ?? this.sessionId,
    parentX: parentX ?? this.parentX,
    parentY: parentY ?? this.parentY,
    parentZoom: parentZoom ?? this.parentZoom,
    bitmap: bitmap ?? this.bitmap,
    setBitCount: setBitCount ?? this.setBitCount,
    updatedAtUtc: updatedAtUtc ?? this.updatedAtUtc,
  );
  TRevealedTilesData copyWithCompanion(TRevealedTilesCompanion data) {
    return TRevealedTilesData(
      id: data.id.present ? data.id.value : this.id,
      sessionId: data.sessionId.present ? data.sessionId.value : this.sessionId,
      parentX: data.parentX.present ? data.parentX.value : this.parentX,
      parentY: data.parentY.present ? data.parentY.value : this.parentY,
      parentZoom: data.parentZoom.present
          ? data.parentZoom.value
          : this.parentZoom,
      bitmap: data.bitmap.present ? data.bitmap.value : this.bitmap,
      setBitCount: data.setBitCount.present
          ? data.setBitCount.value
          : this.setBitCount,
      updatedAtUtc: data.updatedAtUtc.present
          ? data.updatedAtUtc.value
          : this.updatedAtUtc,
    );
  }

  @override
  String toString() {
    return (StringBuffer('TRevealedTilesData(')
          ..write('id: $id, ')
          ..write('sessionId: $sessionId, ')
          ..write('parentX: $parentX, ')
          ..write('parentY: $parentY, ')
          ..write('parentZoom: $parentZoom, ')
          ..write('bitmap: $bitmap, ')
          ..write('setBitCount: $setBitCount, ')
          ..write('updatedAtUtc: $updatedAtUtc')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    sessionId,
    parentX,
    parentY,
    parentZoom,
    $driftBlobEquality.hash(bitmap),
    setBitCount,
    updatedAtUtc,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is TRevealedTilesData &&
          other.id == this.id &&
          other.sessionId == this.sessionId &&
          other.parentX == this.parentX &&
          other.parentY == this.parentY &&
          other.parentZoom == this.parentZoom &&
          $driftBlobEquality.equals(other.bitmap, this.bitmap) &&
          other.setBitCount == this.setBitCount &&
          other.updatedAtUtc == this.updatedAtUtc);
}

class TRevealedTilesCompanion extends UpdateCompanion<TRevealedTilesData> {
  final Value<String> id;
  final Value<String> sessionId;
  final Value<int> parentX;
  final Value<int> parentY;
  final Value<int> parentZoom;
  final Value<i2.Uint8List> bitmap;
  final Value<int> setBitCount;
  final Value<int> updatedAtUtc;
  final Value<int> rowid;
  const TRevealedTilesCompanion({
    this.id = const Value.absent(),
    this.sessionId = const Value.absent(),
    this.parentX = const Value.absent(),
    this.parentY = const Value.absent(),
    this.parentZoom = const Value.absent(),
    this.bitmap = const Value.absent(),
    this.setBitCount = const Value.absent(),
    this.updatedAtUtc = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  TRevealedTilesCompanion.insert({
    required String id,
    required String sessionId,
    required int parentX,
    required int parentY,
    this.parentZoom = const Value.absent(),
    required i2.Uint8List bitmap,
    this.setBitCount = const Value.absent(),
    required int updatedAtUtc,
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       sessionId = Value(sessionId),
       parentX = Value(parentX),
       parentY = Value(parentY),
       bitmap = Value(bitmap),
       updatedAtUtc = Value(updatedAtUtc);
  static Insertable<TRevealedTilesData> custom({
    Expression<String>? id,
    Expression<String>? sessionId,
    Expression<int>? parentX,
    Expression<int>? parentY,
    Expression<int>? parentZoom,
    Expression<i2.Uint8List>? bitmap,
    Expression<int>? setBitCount,
    Expression<int>? updatedAtUtc,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (sessionId != null) 'session_id': sessionId,
      if (parentX != null) 'parent_x': parentX,
      if (parentY != null) 'parent_y': parentY,
      if (parentZoom != null) 'parent_zoom': parentZoom,
      if (bitmap != null) 'bitmap': bitmap,
      if (setBitCount != null) 'set_bit_count': setBitCount,
      if (updatedAtUtc != null) 'updated_at_utc': updatedAtUtc,
      if (rowid != null) 'rowid': rowid,
    });
  }

  TRevealedTilesCompanion copyWith({
    Value<String>? id,
    Value<String>? sessionId,
    Value<int>? parentX,
    Value<int>? parentY,
    Value<int>? parentZoom,
    Value<i2.Uint8List>? bitmap,
    Value<int>? setBitCount,
    Value<int>? updatedAtUtc,
    Value<int>? rowid,
  }) {
    return TRevealedTilesCompanion(
      id: id ?? this.id,
      sessionId: sessionId ?? this.sessionId,
      parentX: parentX ?? this.parentX,
      parentY: parentY ?? this.parentY,
      parentZoom: parentZoom ?? this.parentZoom,
      bitmap: bitmap ?? this.bitmap,
      setBitCount: setBitCount ?? this.setBitCount,
      updatedAtUtc: updatedAtUtc ?? this.updatedAtUtc,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (sessionId.present) {
      map['session_id'] = Variable<String>(sessionId.value);
    }
    if (parentX.present) {
      map['parent_x'] = Variable<int>(parentX.value);
    }
    if (parentY.present) {
      map['parent_y'] = Variable<int>(parentY.value);
    }
    if (parentZoom.present) {
      map['parent_zoom'] = Variable<int>(parentZoom.value);
    }
    if (bitmap.present) {
      map['bitmap'] = Variable<i2.Uint8List>(bitmap.value);
    }
    if (setBitCount.present) {
      map['set_bit_count'] = Variable<int>(setBitCount.value);
    }
    if (updatedAtUtc.present) {
      map['updated_at_utc'] = Variable<int>(updatedAtUtc.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('TRevealedTilesCompanion(')
          ..write('id: $id, ')
          ..write('sessionId: $sessionId, ')
          ..write('parentX: $parentX, ')
          ..write('parentY: $parentY, ')
          ..write('parentZoom: $parentZoom, ')
          ..write('bitmap: $bitmap, ')
          ..write('setBitCount: $setBitCount, ')
          ..write('updatedAtUtc: $updatedAtUtc, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class TMirkStyles extends Table with TableInfo<TMirkStyles, TMirkStylesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  TMirkStyles(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> displayName = GeneratedColumn<String>(
    'display_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> rendererType = GeneratedColumn<String>(
    'renderer_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> config = GeneratedColumn<String>(
    'config',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> createdAtUtc = GeneratedColumn<int>(
    'created_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> createdAtOffsetMinutes = GeneratedColumn<int>(
    'created_at_offset_minutes',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    displayName,
    rendererType,
    config,
    createdAtUtc,
    createdAtOffsetMinutes,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 't_mirk_styles';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  TMirkStylesData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return TMirkStylesData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      displayName: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}display_name'],
      )!,
      rendererType: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}renderer_type'],
      )!,
      config: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}config'],
      )!,
      createdAtUtc: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at_utc'],
      )!,
      createdAtOffsetMinutes: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at_offset_minutes'],
      )!,
    );
  }

  @override
  TMirkStyles createAlias(String alias) {
    return TMirkStyles(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class TMirkStylesData extends DataClass implements Insertable<TMirkStylesData> {
  final String id;
  final String displayName;
  final String rendererType;
  final String config;
  final int createdAtUtc;
  final int createdAtOffsetMinutes;
  const TMirkStylesData({
    required this.id,
    required this.displayName,
    required this.rendererType,
    required this.config,
    required this.createdAtUtc,
    required this.createdAtOffsetMinutes,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['display_name'] = Variable<String>(displayName);
    map['renderer_type'] = Variable<String>(rendererType);
    map['config'] = Variable<String>(config);
    map['created_at_utc'] = Variable<int>(createdAtUtc);
    map['created_at_offset_minutes'] = Variable<int>(createdAtOffsetMinutes);
    return map;
  }

  TMirkStylesCompanion toCompanion(bool nullToAbsent) {
    return TMirkStylesCompanion(
      id: Value(id),
      displayName: Value(displayName),
      rendererType: Value(rendererType),
      config: Value(config),
      createdAtUtc: Value(createdAtUtc),
      createdAtOffsetMinutes: Value(createdAtOffsetMinutes),
    );
  }

  factory TMirkStylesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return TMirkStylesData(
      id: serializer.fromJson<String>(json['id']),
      displayName: serializer.fromJson<String>(json['displayName']),
      rendererType: serializer.fromJson<String>(json['rendererType']),
      config: serializer.fromJson<String>(json['config']),
      createdAtUtc: serializer.fromJson<int>(json['createdAtUtc']),
      createdAtOffsetMinutes: serializer.fromJson<int>(
        json['createdAtOffsetMinutes'],
      ),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'displayName': serializer.toJson<String>(displayName),
      'rendererType': serializer.toJson<String>(rendererType),
      'config': serializer.toJson<String>(config),
      'createdAtUtc': serializer.toJson<int>(createdAtUtc),
      'createdAtOffsetMinutes': serializer.toJson<int>(createdAtOffsetMinutes),
    };
  }

  TMirkStylesData copyWith({
    String? id,
    String? displayName,
    String? rendererType,
    String? config,
    int? createdAtUtc,
    int? createdAtOffsetMinutes,
  }) => TMirkStylesData(
    id: id ?? this.id,
    displayName: displayName ?? this.displayName,
    rendererType: rendererType ?? this.rendererType,
    config: config ?? this.config,
    createdAtUtc: createdAtUtc ?? this.createdAtUtc,
    createdAtOffsetMinutes:
        createdAtOffsetMinutes ?? this.createdAtOffsetMinutes,
  );
  TMirkStylesData copyWithCompanion(TMirkStylesCompanion data) {
    return TMirkStylesData(
      id: data.id.present ? data.id.value : this.id,
      displayName: data.displayName.present
          ? data.displayName.value
          : this.displayName,
      rendererType: data.rendererType.present
          ? data.rendererType.value
          : this.rendererType,
      config: data.config.present ? data.config.value : this.config,
      createdAtUtc: data.createdAtUtc.present
          ? data.createdAtUtc.value
          : this.createdAtUtc,
      createdAtOffsetMinutes: data.createdAtOffsetMinutes.present
          ? data.createdAtOffsetMinutes.value
          : this.createdAtOffsetMinutes,
    );
  }

  @override
  String toString() {
    return (StringBuffer('TMirkStylesData(')
          ..write('id: $id, ')
          ..write('displayName: $displayName, ')
          ..write('rendererType: $rendererType, ')
          ..write('config: $config, ')
          ..write('createdAtUtc: $createdAtUtc, ')
          ..write('createdAtOffsetMinutes: $createdAtOffsetMinutes')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    displayName,
    rendererType,
    config,
    createdAtUtc,
    createdAtOffsetMinutes,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is TMirkStylesData &&
          other.id == this.id &&
          other.displayName == this.displayName &&
          other.rendererType == this.rendererType &&
          other.config == this.config &&
          other.createdAtUtc == this.createdAtUtc &&
          other.createdAtOffsetMinutes == this.createdAtOffsetMinutes);
}

class TMirkStylesCompanion extends UpdateCompanion<TMirkStylesData> {
  final Value<String> id;
  final Value<String> displayName;
  final Value<String> rendererType;
  final Value<String> config;
  final Value<int> createdAtUtc;
  final Value<int> createdAtOffsetMinutes;
  final Value<int> rowid;
  const TMirkStylesCompanion({
    this.id = const Value.absent(),
    this.displayName = const Value.absent(),
    this.rendererType = const Value.absent(),
    this.config = const Value.absent(),
    this.createdAtUtc = const Value.absent(),
    this.createdAtOffsetMinutes = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  TMirkStylesCompanion.insert({
    required String id,
    required String displayName,
    required String rendererType,
    required String config,
    required int createdAtUtc,
    required int createdAtOffsetMinutes,
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       displayName = Value(displayName),
       rendererType = Value(rendererType),
       config = Value(config),
       createdAtUtc = Value(createdAtUtc),
       createdAtOffsetMinutes = Value(createdAtOffsetMinutes);
  static Insertable<TMirkStylesData> custom({
    Expression<String>? id,
    Expression<String>? displayName,
    Expression<String>? rendererType,
    Expression<String>? config,
    Expression<int>? createdAtUtc,
    Expression<int>? createdAtOffsetMinutes,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (displayName != null) 'display_name': displayName,
      if (rendererType != null) 'renderer_type': rendererType,
      if (config != null) 'config': config,
      if (createdAtUtc != null) 'created_at_utc': createdAtUtc,
      if (createdAtOffsetMinutes != null)
        'created_at_offset_minutes': createdAtOffsetMinutes,
      if (rowid != null) 'rowid': rowid,
    });
  }

  TMirkStylesCompanion copyWith({
    Value<String>? id,
    Value<String>? displayName,
    Value<String>? rendererType,
    Value<String>? config,
    Value<int>? createdAtUtc,
    Value<int>? createdAtOffsetMinutes,
    Value<int>? rowid,
  }) {
    return TMirkStylesCompanion(
      id: id ?? this.id,
      displayName: displayName ?? this.displayName,
      rendererType: rendererType ?? this.rendererType,
      config: config ?? this.config,
      createdAtUtc: createdAtUtc ?? this.createdAtUtc,
      createdAtOffsetMinutes:
          createdAtOffsetMinutes ?? this.createdAtOffsetMinutes,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (displayName.present) {
      map['display_name'] = Variable<String>(displayName.value);
    }
    if (rendererType.present) {
      map['renderer_type'] = Variable<String>(rendererType.value);
    }
    if (config.present) {
      map['config'] = Variable<String>(config.value);
    }
    if (createdAtUtc.present) {
      map['created_at_utc'] = Variable<int>(createdAtUtc.value);
    }
    if (createdAtOffsetMinutes.present) {
      map['created_at_offset_minutes'] = Variable<int>(
        createdAtOffsetMinutes.value,
      );
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('TMirkStylesCompanion(')
          ..write('id: $id, ')
          ..write('displayName: $displayName, ')
          ..write('rendererType: $rendererType, ')
          ..write('config: $config, ')
          ..write('createdAtUtc: $createdAtUtc, ')
          ..write('createdAtOffsetMinutes: $createdAtOffsetMinutes, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class TPhotos extends Table with TableInfo<TPhotos, TPhotosData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  TPhotos(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> id = GeneratedColumn<String>(
    'id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> markerId = GeneratedColumn<String>(
    'marker_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES t_markers(id)ON DELETE CASCADE',
  );
  late final GeneratedColumn<String> relativeBasename = GeneratedColumn<String>(
    'relative_basename',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> widthPx = GeneratedColumn<int>(
    'width_px',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> heightPx = GeneratedColumn<int>(
    'height_px',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> fileSizeBytes = GeneratedColumn<int>(
    'file_size_bytes',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> createdAtUtc = GeneratedColumn<int>(
    'created_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> createdAtOffsetMinutes = GeneratedColumn<int>(
    'created_at_offset_minutes',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    id,
    markerId,
    relativeBasename,
    widthPx,
    heightPx,
    fileSizeBytes,
    createdAtUtc,
    createdAtOffsetMinutes,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 't_photos';
  @override
  Set<GeneratedColumn> get $primaryKey => {id};
  @override
  TPhotosData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return TPhotosData(
      id: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}id'],
      )!,
      markerId: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}marker_id'],
      )!,
      relativeBasename: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}relative_basename'],
      )!,
      widthPx: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}width_px'],
      )!,
      heightPx: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}height_px'],
      )!,
      fileSizeBytes: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}file_size_bytes'],
      )!,
      createdAtUtc: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at_utc'],
      )!,
      createdAtOffsetMinutes: attachedDatabase.typeMapping.read(
        DriftSqlType.int,
        data['${effectivePrefix}created_at_offset_minutes'],
      )!,
    );
  }

  @override
  TPhotos createAlias(String alias) {
    return TPhotos(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(id)'];
  @override
  bool get dontWriteConstraints => true;
}

class TPhotosData extends DataClass implements Insertable<TPhotosData> {
  final String id;
  final String markerId;
  final String relativeBasename;
  final int widthPx;
  final int heightPx;
  final int fileSizeBytes;
  final int createdAtUtc;
  final int createdAtOffsetMinutes;
  const TPhotosData({
    required this.id,
    required this.markerId,
    required this.relativeBasename,
    required this.widthPx,
    required this.heightPx,
    required this.fileSizeBytes,
    required this.createdAtUtc,
    required this.createdAtOffsetMinutes,
  });
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['marker_id'] = Variable<String>(markerId);
    map['relative_basename'] = Variable<String>(relativeBasename);
    map['width_px'] = Variable<int>(widthPx);
    map['height_px'] = Variable<int>(heightPx);
    map['file_size_bytes'] = Variable<int>(fileSizeBytes);
    map['created_at_utc'] = Variable<int>(createdAtUtc);
    map['created_at_offset_minutes'] = Variable<int>(createdAtOffsetMinutes);
    return map;
  }

  TPhotosCompanion toCompanion(bool nullToAbsent) {
    return TPhotosCompanion(
      id: Value(id),
      markerId: Value(markerId),
      relativeBasename: Value(relativeBasename),
      widthPx: Value(widthPx),
      heightPx: Value(heightPx),
      fileSizeBytes: Value(fileSizeBytes),
      createdAtUtc: Value(createdAtUtc),
      createdAtOffsetMinutes: Value(createdAtOffsetMinutes),
    );
  }

  factory TPhotosData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return TPhotosData(
      id: serializer.fromJson<String>(json['id']),
      markerId: serializer.fromJson<String>(json['markerId']),
      relativeBasename: serializer.fromJson<String>(json['relativeBasename']),
      widthPx: serializer.fromJson<int>(json['widthPx']),
      heightPx: serializer.fromJson<int>(json['heightPx']),
      fileSizeBytes: serializer.fromJson<int>(json['fileSizeBytes']),
      createdAtUtc: serializer.fromJson<int>(json['createdAtUtc']),
      createdAtOffsetMinutes: serializer.fromJson<int>(
        json['createdAtOffsetMinutes'],
      ),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'markerId': serializer.toJson<String>(markerId),
      'relativeBasename': serializer.toJson<String>(relativeBasename),
      'widthPx': serializer.toJson<int>(widthPx),
      'heightPx': serializer.toJson<int>(heightPx),
      'fileSizeBytes': serializer.toJson<int>(fileSizeBytes),
      'createdAtUtc': serializer.toJson<int>(createdAtUtc),
      'createdAtOffsetMinutes': serializer.toJson<int>(createdAtOffsetMinutes),
    };
  }

  TPhotosData copyWith({
    String? id,
    String? markerId,
    String? relativeBasename,
    int? widthPx,
    int? heightPx,
    int? fileSizeBytes,
    int? createdAtUtc,
    int? createdAtOffsetMinutes,
  }) => TPhotosData(
    id: id ?? this.id,
    markerId: markerId ?? this.markerId,
    relativeBasename: relativeBasename ?? this.relativeBasename,
    widthPx: widthPx ?? this.widthPx,
    heightPx: heightPx ?? this.heightPx,
    fileSizeBytes: fileSizeBytes ?? this.fileSizeBytes,
    createdAtUtc: createdAtUtc ?? this.createdAtUtc,
    createdAtOffsetMinutes:
        createdAtOffsetMinutes ?? this.createdAtOffsetMinutes,
  );
  TPhotosData copyWithCompanion(TPhotosCompanion data) {
    return TPhotosData(
      id: data.id.present ? data.id.value : this.id,
      markerId: data.markerId.present ? data.markerId.value : this.markerId,
      relativeBasename: data.relativeBasename.present
          ? data.relativeBasename.value
          : this.relativeBasename,
      widthPx: data.widthPx.present ? data.widthPx.value : this.widthPx,
      heightPx: data.heightPx.present ? data.heightPx.value : this.heightPx,
      fileSizeBytes: data.fileSizeBytes.present
          ? data.fileSizeBytes.value
          : this.fileSizeBytes,
      createdAtUtc: data.createdAtUtc.present
          ? data.createdAtUtc.value
          : this.createdAtUtc,
      createdAtOffsetMinutes: data.createdAtOffsetMinutes.present
          ? data.createdAtOffsetMinutes.value
          : this.createdAtOffsetMinutes,
    );
  }

  @override
  String toString() {
    return (StringBuffer('TPhotosData(')
          ..write('id: $id, ')
          ..write('markerId: $markerId, ')
          ..write('relativeBasename: $relativeBasename, ')
          ..write('widthPx: $widthPx, ')
          ..write('heightPx: $heightPx, ')
          ..write('fileSizeBytes: $fileSizeBytes, ')
          ..write('createdAtUtc: $createdAtUtc, ')
          ..write('createdAtOffsetMinutes: $createdAtOffsetMinutes')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(
    id,
    markerId,
    relativeBasename,
    widthPx,
    heightPx,
    fileSizeBytes,
    createdAtUtc,
    createdAtOffsetMinutes,
  );
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is TPhotosData &&
          other.id == this.id &&
          other.markerId == this.markerId &&
          other.relativeBasename == this.relativeBasename &&
          other.widthPx == this.widthPx &&
          other.heightPx == this.heightPx &&
          other.fileSizeBytes == this.fileSizeBytes &&
          other.createdAtUtc == this.createdAtUtc &&
          other.createdAtOffsetMinutes == this.createdAtOffsetMinutes);
}

class TPhotosCompanion extends UpdateCompanion<TPhotosData> {
  final Value<String> id;
  final Value<String> markerId;
  final Value<String> relativeBasename;
  final Value<int> widthPx;
  final Value<int> heightPx;
  final Value<int> fileSizeBytes;
  final Value<int> createdAtUtc;
  final Value<int> createdAtOffsetMinutes;
  final Value<int> rowid;
  const TPhotosCompanion({
    this.id = const Value.absent(),
    this.markerId = const Value.absent(),
    this.relativeBasename = const Value.absent(),
    this.widthPx = const Value.absent(),
    this.heightPx = const Value.absent(),
    this.fileSizeBytes = const Value.absent(),
    this.createdAtUtc = const Value.absent(),
    this.createdAtOffsetMinutes = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  TPhotosCompanion.insert({
    required String id,
    required String markerId,
    required String relativeBasename,
    required int widthPx,
    required int heightPx,
    required int fileSizeBytes,
    required int createdAtUtc,
    required int createdAtOffsetMinutes,
    this.rowid = const Value.absent(),
  }) : id = Value(id),
       markerId = Value(markerId),
       relativeBasename = Value(relativeBasename),
       widthPx = Value(widthPx),
       heightPx = Value(heightPx),
       fileSizeBytes = Value(fileSizeBytes),
       createdAtUtc = Value(createdAtUtc),
       createdAtOffsetMinutes = Value(createdAtOffsetMinutes);
  static Insertable<TPhotosData> custom({
    Expression<String>? id,
    Expression<String>? markerId,
    Expression<String>? relativeBasename,
    Expression<int>? widthPx,
    Expression<int>? heightPx,
    Expression<int>? fileSizeBytes,
    Expression<int>? createdAtUtc,
    Expression<int>? createdAtOffsetMinutes,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (markerId != null) 'marker_id': markerId,
      if (relativeBasename != null) 'relative_basename': relativeBasename,
      if (widthPx != null) 'width_px': widthPx,
      if (heightPx != null) 'height_px': heightPx,
      if (fileSizeBytes != null) 'file_size_bytes': fileSizeBytes,
      if (createdAtUtc != null) 'created_at_utc': createdAtUtc,
      if (createdAtOffsetMinutes != null)
        'created_at_offset_minutes': createdAtOffsetMinutes,
      if (rowid != null) 'rowid': rowid,
    });
  }

  TPhotosCompanion copyWith({
    Value<String>? id,
    Value<String>? markerId,
    Value<String>? relativeBasename,
    Value<int>? widthPx,
    Value<int>? heightPx,
    Value<int>? fileSizeBytes,
    Value<int>? createdAtUtc,
    Value<int>? createdAtOffsetMinutes,
    Value<int>? rowid,
  }) {
    return TPhotosCompanion(
      id: id ?? this.id,
      markerId: markerId ?? this.markerId,
      relativeBasename: relativeBasename ?? this.relativeBasename,
      widthPx: widthPx ?? this.widthPx,
      heightPx: heightPx ?? this.heightPx,
      fileSizeBytes: fileSizeBytes ?? this.fileSizeBytes,
      createdAtUtc: createdAtUtc ?? this.createdAtUtc,
      createdAtOffsetMinutes:
          createdAtOffsetMinutes ?? this.createdAtOffsetMinutes,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) {
      map['id'] = Variable<String>(id.value);
    }
    if (markerId.present) {
      map['marker_id'] = Variable<String>(markerId.value);
    }
    if (relativeBasename.present) {
      map['relative_basename'] = Variable<String>(relativeBasename.value);
    }
    if (widthPx.present) {
      map['width_px'] = Variable<int>(widthPx.value);
    }
    if (heightPx.present) {
      map['height_px'] = Variable<int>(heightPx.value);
    }
    if (fileSizeBytes.present) {
      map['file_size_bytes'] = Variable<int>(fileSizeBytes.value);
    }
    if (createdAtUtc.present) {
      map['created_at_utc'] = Variable<int>(createdAtUtc.value);
    }
    if (createdAtOffsetMinutes.present) {
      map['created_at_offset_minutes'] = Variable<int>(
        createdAtOffsetMinutes.value,
      );
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('TPhotosCompanion(')
          ..write('id: $id, ')
          ..write('markerId: $markerId, ')
          ..write('relativeBasename: $relativeBasename, ')
          ..write('widthPx: $widthPx, ')
          ..write('heightPx: $heightPx, ')
          ..write('fileSizeBytes: $fileSizeBytes, ')
          ..write('createdAtUtc: $createdAtUtc, ')
          ..write('createdAtOffsetMinutes: $createdAtOffsetMinutes, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DatabaseAtV2 extends GeneratedDatabase {
  DatabaseAtV2(QueryExecutor e) : super(e);
  late final TSessions tSessions = TSessions(this);
  late final TMarkerCategories tMarkerCategories = TMarkerCategories(this);
  late final TMarkers tMarkers = TMarkers(this);
  late final TRevealedTiles tRevealedTiles = TRevealedTiles(this);
  late final TMirkStyles tMirkStyles = TMirkStyles(this);
  late final TPhotos tPhotos = TPhotos(this);
  late final Index idxTSessionsStatusActive = Index(
    'idx_t_sessions_status_active',
    'CREATE UNIQUE INDEX idx_t_sessions_status_active ON t_sessions (status) WHERE status = \'active\'',
  );
  late final Index idxTMarkersSessionId = Index(
    'idx_t_markers_session_id',
    'CREATE INDEX idx_t_markers_session_id ON t_markers (session_id)',
  );
  late final Index idxTMarkersCategoryId = Index(
    'idx_t_markers_category_id',
    'CREATE INDEX idx_t_markers_category_id ON t_markers (category_id)',
  );
  late final Index idxTRevealedTilesSessionIdParentKey = Index(
    'idx_t_revealed_tiles_session_id_parent_key',
    'CREATE INDEX idx_t_revealed_tiles_session_id_parent_key ON t_revealed_tiles (session_id, parent_x, parent_y)',
  );
  late final Index idxTPhotosMarkerId = Index(
    'idx_t_photos_marker_id',
    'CREATE INDEX idx_t_photos_marker_id ON t_photos (marker_id)',
  );
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    tSessions,
    tMarkerCategories,
    tMarkers,
    tRevealedTiles,
    tMirkStyles,
    tPhotos,
    idxTSessionsStatusActive,
    idxTMarkersSessionId,
    idxTMarkersCategoryId,
    idxTRevealedTilesSessionIdParentKey,
    idxTPhotosMarkerId,
  ];
  @override
  StreamQueryUpdateRules get streamUpdateRules => const StreamQueryUpdateRules([
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        't_sessions',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('t_markers', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        't_sessions',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('t_revealed_tiles', kind: UpdateKind.delete)],
    ),
    WritePropagation(
      on: TableUpdateQuery.onTableName(
        't_markers',
        limitUpdateKind: UpdateKind.delete,
      ),
      result: [TableUpdate('t_photos', kind: UpdateKind.delete)],
    ),
  ]);
  @override
  int get schemaVersion => 2;
}
