// Copyright (c) 2026 THONGVAN Alexis
// Licensed under the Good Old Software License v1.0
// See LICENSE file for details

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import '../check_domain_purity.dart' as check_domain_purity;

/// Fixture-based tests for `tool/check_domain_purity.dart`.
///
/// Each test materialises a synthetic `lib/domain/` tree under
/// `Directory.systemTemp`, invokes `runCheck` against it, and asserts on
/// the return code (the CI contract — stderr wording is treated as
/// implementation detail). Mirrors the structure of
/// `tool/test/check_headers_test.dart` so the family stays consistent.
const String _gosl = '''// Copyright (c) 2026 THONGVAN Alexis
// Licensed under the Good Old Software License v1.0
// See LICENSE file for details
''';

void main() {
  group('check_domain_purity.runCheck', () {
    late Directory tempDir;
    late String domainRoot;

    setUp(() async {
      tempDir = await Directory.systemTemp.createTemp('check_domain_purity_test_');
      domainRoot = p.join(tempDir.path, 'lib', 'domain');
      await Directory(domainRoot).create(recursive: true);
    });

    tearDown(() async {
      if (await tempDir.exists()) {
        await tempDir.delete(recursive: true);
      }
    });

    test('returns 0 when every domain .dart file imports only pure Dart', () async {
      await File(p.join(domainRoot, 'session.dart')).writeAsString('$_gosl\nimport \'dart:async\';\nimport \'dart:convert\';\n\nclass Session {}\n');
      await File(p.join(domainRoot, 'marker.dart')).writeAsString('$_gosl\n// no imports\nclass Marker {}\n');

      final int code = await check_domain_purity.runCheck(rootPath: domainRoot);
      expect(code, 0);
    });

    test('returns 1 when a domain file imports package:flutter', () async {
      await File(p.join(domainRoot, 'session.dart')).writeAsString('$_gosl\nimport \'dart:async\';\n\nclass Session {}\n');
      await File(p.join(domainRoot, 'bad_widget.dart')).writeAsString('$_gosl\nimport \'package:flutter/material.dart\';\n\nclass BadDomainWidget {}\n');

      final int code = await check_domain_purity.runCheck(rootPath: domainRoot);
      expect(code, 1);
    });

    test('returns 1 when a domain file imports package:drift', () async {
      await File(p.join(domainRoot, 'bad_drift.dart')).writeAsString('$_gosl\nimport \'package:drift/drift.dart\';\n\nclass DomainWithDrift {}\n');

      final int code = await check_domain_purity.runCheck(rootPath: domainRoot);
      expect(code, 1);
    });

    test('returns 1 when a domain file imports package:drift_flutter '
        '(finding #31 / Batch J — drift_flutter is Flutter-coupled)', () async {
      await File(
        p.join(domainRoot, 'bad_drift_flutter.dart'),
      ).writeAsString('$_gosl\nimport \'package:drift_flutter/drift_flutter.dart\';\n\nclass DomainWithDriftFlutter {}\n');

      final int code = await check_domain_purity.runCheck(rootPath: domainRoot);
      expect(code, 1);
    });

    test('returns 2 when lib/domain/ does not exist (misconfiguration)', () async {
      final int code = await check_domain_purity.runCheck(rootPath: p.join(tempDir.path, 'nonexistent_domain'));
      expect(code, 2);
    });

    test('exempts generated files (.g.dart, .freezed.dart) from the scan', () async {
      // Generated outputs are produced from annotated source — they may
      // legitimately need package:flutter or package:drift imports the
      // hand-written domain code does not. Excluding them keeps the rule
      // applied to source we control.
      await File(p.join(domainRoot, 'good.dart')).writeAsString('$_gosl\nimport \'dart:async\';\n\nclass Good {}\n');
      await File(
        p.join(domainRoot, 'session.g.dart'),
      ).writeAsString('// generated by build_runner\nimport \'package:drift/drift.dart\';\n\nclass GenImpl {}\n');
      await File(
        p.join(domainRoot, 'marker.freezed.dart'),
      ).writeAsString('// generated by freezed\nimport \'package:flutter/foundation.dart\';\n\nclass Frz {}\n');

      final int code = await check_domain_purity.runCheck(rootPath: domainRoot);
      expect(code, 0);
    });
  });
}
