// Copyright (c) 2026 THONGVAN Alexis
// Licensed under the Good Old Software License v1.0
// See LICENSE file for details

import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import '../simplify_polygons.dart' as simplify;

/// Fixture-based paired tests for `tool/simplify_polygons.dart`.
///
/// The script's `runCheck({sourceDir, outputDir})` seam drives the
/// pipeline against synthetic GeoJSON fixtures in a tempdir — the real
/// `C:\\claude_checkouts\\countries\\data` tree is not touched.
///
/// Covers the documented exit-code contract (Phase 01 CLI convention):
///   exit 0 — all files processed cleanly
///   exit 1 — at least one file was skipped (unparseable / empty coords)
///   exit 2 — misconfiguration (source dir missing)
///
/// Plus the deterministic-ordering + bbox-correctness invariants.

/// Fabricates a minimal GeoJSON FeatureCollection with a single Polygon
/// covering the bounding rectangle `[minLon..maxLon] x [minLat..maxLat]`.
String _rectPolygon({required String alpha3, required double minLon, required double maxLon, required double minLat, required double maxLat}) {
  return jsonEncode(<String, Object?>{
    'type': 'FeatureCollection',
    'features': <Object?>[
      <String, Object?>{
        'type': 'Feature',
        'properties': <String, Object?>{'alpha3': alpha3},
        'geometry': <String, Object?>{
          'type': 'Polygon',
          'coordinates': <Object?>[
            <Object?>[
              <double>[minLon, minLat],
              <double>[maxLon, minLat],
              <double>[maxLon, maxLat],
              <double>[minLon, maxLat],
              <double>[minLon, minLat],
            ],
          ],
        },
      },
    ],
  });
}

void main() {
  group('simplify_polygons.runCheck', () {
    late Directory tempDir;
    late String sourceDir;
    late String outputDir;

    setUp(() async {
      tempDir = await Directory.systemTemp.createTemp('simplify_polygons_test_');
      sourceDir = p.join(tempDir.path, 'source');
      outputDir = p.join(tempDir.path, 'output');
      Directory(sourceDir).createSync(recursive: true);
    });

    tearDown(() async {
      if (tempDir.existsSync()) {
        try {
          await tempDir.delete(recursive: true);
        } on FileSystemException {
          // Swallow — Windows temp cleanup, same as Phase 01 convention.
        }
      }
    });

    test('processes polygons + emits bbox FeatureCollections + exit 0', () async {
      // FRA approx bbox: lon ∈ [-5, 8.5], lat ∈ [42, 51].
      File(p.join(sourceDir, 'fra.geo.json')).writeAsStringSync(_rectPolygon(alpha3: 'fra', minLon: -5.0, maxLon: 8.5, minLat: 42.0, maxLat: 51.0));

      final int code = await simplify.runCheck(sourceDir: sourceDir, outputDir: outputDir);
      expect(code, equals(0));

      final File out = File(p.join(outputDir, 'fra.geo.json'));
      expect(out.existsSync(), isTrue);
      final Map<String, Object?> decoded = jsonDecode(out.readAsStringSync()) as Map<String, Object?>;
      expect(decoded['type'], equals('FeatureCollection'));

      final Map<String, Object?> feature = (decoded['features']! as List).first as Map<String, Object?>;
      final Map<String, Object?> geometry = feature['geometry']! as Map<String, Object?>;
      expect(geometry['type'], equals('Polygon'));
      final List<Object?> ring = ((geometry['coordinates']! as List).first as List);
      // 5-vertex closed ring [minLon,minLat] → [maxLon,minLat] → [maxLon,maxLat] → [minLon,maxLat] → [minLon,minLat]
      expect(ring, hasLength(5));
      final List<Object?> first = ring.first as List<Object?>;
      final List<Object?> last = ring.last as List<Object?>;
      expect(first, equals(last), reason: 'ring must close on itself');
      expect((first[0] as num).toDouble(), equals(-5.0));
      expect((first[1] as num).toDouble(), equals(42.0));
    });

    test('emits INDEX.md sidecar documenting the machine-generated nature', () async {
      File(p.join(sourceDir, 'deu.geo.json')).writeAsStringSync(_rectPolygon(alpha3: 'deu', minLon: 5.9, maxLon: 15.0, minLat: 47.3, maxLat: 55.0));

      expect(await simplify.runCheck(sourceDir: sourceDir, outputDir: outputDir), equals(0));

      final File indexFile = File(p.join(outputDir, 'INDEX.md'));
      expect(indexFile.existsSync(), isTrue);
      final String contents = indexFile.readAsStringSync();
      expect(contents, contains('Machine-generated by `tool/simplify_polygons.dart`'));
      expect(contents, contains('**1** files processed'));
      expect(contents, contains('Do NOT hand-edit'));
    });

    test('skips unparseable JSON + exit 1 (remaining files still processed)', () async {
      File(p.join(sourceDir, 'good.geo.json')).writeAsStringSync(_rectPolygon(alpha3: 'good', minLon: 0, maxLon: 1, minLat: 0, maxLat: 1));
      File(p.join(sourceDir, 'bad.geo.json')).writeAsStringSync('this is not JSON');

      final int code = await simplify.runCheck(sourceDir: sourceDir, outputDir: outputDir);
      expect(code, equals(1));
      // Good file still produced output.
      expect(File(p.join(outputDir, 'good.geo.json')).existsSync(), isTrue);
      // Bad file did not.
      expect(File(p.join(outputDir, 'bad.geo.json')).existsSync(), isFalse);
    });

    test('returns 2 when source directory is missing', () async {
      final String missingSource = p.join(tempDir.path, 'nonexistent');
      final int code = await simplify.runCheck(sourceDir: missingSource, outputDir: outputDir);
      expect(code, equals(2));
    });

    test('skips empty-coordinates GeoJSON + exit 1', () async {
      File(p.join(sourceDir, 'empty.geo.json')).writeAsStringSync(jsonEncode(<String, Object?>{'type': 'FeatureCollection', 'features': <Object?>[]}));

      expect(await simplify.runCheck(sourceDir: sourceDir, outputDir: outputDir), equals(1));
    });

    test('processes multiple files in deterministic (sorted) order', () async {
      // Write three files. `listSync()` order is filesystem-dependent; the
      // script MUST sort before iterating to keep diffs stable.
      File(p.join(sourceDir, 'zzz.geo.json')).writeAsStringSync(_rectPolygon(alpha3: 'zzz', minLon: 0, maxLon: 1, minLat: 0, maxLat: 1));
      File(p.join(sourceDir, 'aaa.geo.json')).writeAsStringSync(_rectPolygon(alpha3: 'aaa', minLon: 2, maxLon: 3, minLat: 2, maxLat: 3));
      File(p.join(sourceDir, 'mmm.geo.json')).writeAsStringSync(_rectPolygon(alpha3: 'mmm', minLon: 4, maxLon: 5, minLat: 4, maxLat: 5));

      expect(await simplify.runCheck(sourceDir: sourceDir, outputDir: outputDir), equals(0));
      // All three produced output files named after their alpha3.
      for (final String code in <String>['aaa', 'mmm', 'zzz']) {
        expect(File(p.join(outputDir, '$code.geo.json')).existsSync(), isTrue, reason: '$code output missing');
      }
      // Re-read INDEX.md to confirm 3 processed.
      final String indexContents = File(p.join(outputDir, 'INDEX.md')).readAsStringSync();
      expect(indexContents, contains('**3** files processed'));
    });

    test('handles MultiPolygon geometries via nested coordinate walker', () async {
      // Italy-ish MultiPolygon: mainland + Sicily + Sardinia. The bbox
      // covers the union of all three.
      File(p.join(sourceDir, 'ita.geo.json')).writeAsStringSync(
        jsonEncode(<String, Object?>{
          'type': 'FeatureCollection',
          'features': <Object?>[
            <String, Object?>{
              'type': 'Feature',
              'properties': <String, Object?>{'alpha3': 'ita'},
              'geometry': <String, Object?>{
                'type': 'MultiPolygon',
                'coordinates': <Object?>[
                  // mainland ~ [7, 35] → [18, 47]
                  <Object?>[
                    <Object?>[
                      <double>[7.0, 35.0],
                      <double>[18.0, 35.0],
                      <double>[18.0, 47.0],
                      <double>[7.0, 47.0],
                      <double>[7.0, 35.0],
                    ],
                  ],
                  // Sardinia ~ [8, 39] → [10, 41]
                  <Object?>[
                    <Object?>[
                      <double>[8.0, 39.0],
                      <double>[10.0, 39.0],
                      <double>[10.0, 41.0],
                      <double>[8.0, 41.0],
                      <double>[8.0, 39.0],
                    ],
                  ],
                ],
              },
            },
          ],
        }),
      );

      expect(await simplify.runCheck(sourceDir: sourceDir, outputDir: outputDir), equals(0));
      final Map<String, Object?> decoded = jsonDecode(File(p.join(outputDir, 'ita.geo.json')).readAsStringSync()) as Map<String, Object?>;
      final List<Object?> ring = (((decoded['features']! as List).first as Map<String, Object?>)['geometry']! as Map<String, Object?>)['coordinates']! as List;
      final List<Object?> firstPoint = (ring.first as List).first as List;
      // bbox minLon=7.0 minLat=35.0
      expect((firstPoint[0] as num).toDouble(), equals(7.0));
      expect((firstPoint[1] as num).toDouble(), equals(35.0));
    });
  });
}
